//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8745
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace ScheduledTask
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    [System.Xml.Serialization.XmlRootAttribute("Task", Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task", IsNullable = false)]
    public partial class taskType
    {

        /// <remarks/>
        public registrationInfoType RegistrationInfo;

        /// <remarks/>
        public triggersType Triggers;

        /// <remarks/>
        public settingsType Settings;

        /// <remarks/>
        public System.Xml.XmlElement Data;

        /// <remarks/>
        public principalsType Principals;

        /// <remarks/>
        public actionsType Actions;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version;

        public taskType()
        {
            this.version = "1.3";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class registrationInfoType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string URI;

        /// <remarks/>
        public string SecurityDescriptor;

        /// <remarks/>
        public string Source;

        /// <remarks/>
        public System.DateTime Date;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified;

        /// <remarks/>
        public string Author;

        /// <remarks/>
        public string Version;

        /// <remarks/>
        public string Description;

        /// <remarks/>
        public string Documentation;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class headerFieldType
    {

        /// <remarks/>
        public string Name;

        /// <remarks/>
        public string Value;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(showMessageType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sendEmailType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(comHandlerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(execType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public abstract partial class actionBaseType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string id;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class showMessageType : actionBaseType
    {

        /// <remarks/>
        public string Title;

        /// <remarks/>
        public string Body;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class sendEmailType : actionBaseType
    {

        /// <remarks/>
        public string Server;

        /// <remarks/>
        public string Subject;

        /// <remarks/>
        public string To;

        /// <remarks/>
        public string Cc;

        /// <remarks/>
        public string Bcc;

        /// <remarks/>
        public string ReplyTo;

        /// <remarks/>
        public string From;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("HeaderField", IsNullable = false)]
        public headerFieldType[] HeaderFields;

        /// <remarks/>
        public string Body;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("File", IsNullable = false)]
        public string[] Attachments;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class comHandlerType : actionBaseType
    {

        /// <remarks/>
        public string ClassId;

        /// <remarks/>
        public System.Xml.XmlElement Data;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class execType : actionBaseType
    {

        /// <remarks/>
        public string Command;

        /// <remarks/>
        public string Arguments;

        /// <remarks/>
        public string WorkingDirectory;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class actionsType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Exec")]
        public execType[] Exec;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ComHandler")]
        public comHandlerType[] ComHandler;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SendEmail")]
        public sendEmailType[] SendEmail;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShowMessage")]
        public showMessageType[] ShowMessage;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "IDREF")]
        public string Context;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class principalType
    {

        /// <remarks/>
        public string UserId;

        /// <remarks/>
        public logonType LogonType;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LogonTypeSpecified;

        /// <remarks/>
        public string GroupId;

        /// <remarks/>
        public string DisplayName;

        /// <remarks/>
        public runLevelType RunLevel;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RunLevelSpecified;

        /// <remarks/>
        public processTokenSidType ProcessTokenSidType;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProcessTokenSidTypeSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Privilege", IsNullable = false)]
        public privilegeType[] RequiredPrivileges;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string id;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public enum logonType
    {

        /// <remarks/>
        S4U,

        /// <remarks/>
        Password,

        /// <remarks/>
        InteractiveToken,

        /// <remarks/>
        InteractiveTokenOrPassword,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public enum runLevelType
    {

        /// <remarks/>
        LeastPrivilege,

        /// <remarks/>
        HighestAvailable,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public enum processTokenSidType
    {

        /// <remarks/>
        None,

        /// <remarks/>
        Unrestricted,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public enum privilegeType
    {

        /// <remarks/>
        SeCreateTokenPrivilege,

        /// <remarks/>
        SeAssignPrimaryTokenPrivilege,

        /// <remarks/>
        SeLockMemoryPrivilege,

        /// <remarks/>
        SeIncreaseQuotaPrivilege,

        /// <remarks/>
        SeUnsolicitedInputPrivilege,

        /// <remarks/>
        SeMachineAccountPrivilege,

        /// <remarks/>
        SeTcbPrivilege,

        /// <remarks/>
        SeSecurityPrivilege,

        /// <remarks/>
        SeTakeOwnershipPrivilege,

        /// <remarks/>
        SeLoadDriverPrivilege,

        /// <remarks/>
        SeSystemProfilePrivilege,

        /// <remarks/>
        SeSystemtimePrivilege,

        /// <remarks/>
        SeProfileSingleProcessPrivilege,

        /// <remarks/>
        SeIncreaseBasePriorityPrivilege,

        /// <remarks/>
        SeCreatePagefilePrivilege,

        /// <remarks/>
        SeCreatePermanentPrivilege,

        /// <remarks/>
        SeBackupPrivilege,

        /// <remarks/>
        SeRestorePrivilege,

        /// <remarks/>
        SeShutdownPrivilege,

        /// <remarks/>
        SeDebugPrivilege,

        /// <remarks/>
        SeAuditPrivilege,

        /// <remarks/>
        SeSystemEnvironmentPrivilege,

        /// <remarks/>
        SeChangeNotifyPrivilege,

        /// <remarks/>
        SeRemoteShutdownPrivilege,

        /// <remarks/>
        SeUndockPrivilege,

        /// <remarks/>
        SeSyncAgentPrivilege,

        /// <remarks/>
        SeEnableDelegationPrivilege,

        /// <remarks/>
        SeManageVolumePrivilege,

        /// <remarks/>
        SeImpersonatePrivilege,

        /// <remarks/>
        SeCreateGlobalPrivilege,

        /// <remarks/>
        SeTrustedCredManAccessPrivilege,

        /// <remarks/>
        SeRelabelPrivilege,

        /// <remarks/>
        SeIncreaseWorkingSetPrivilege,

        /// <remarks/>
        SeTimeZonePrivilege,

        /// <remarks/>
        SeCreateSymbolicLinkPrivilege,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class principalsType
    {

        /// <remarks/>
        public principalType Principal;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class networkSettingsType
    {

        /// <remarks/>
        public string Name;

        /// <remarks/>
        public string Id;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class idleSettingsType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT10M")]
        public string Duration;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT1H")]
        public string WaitTimeout;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool StopOnIdleEnd;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool RestartOnIdle;

        public idleSettingsType()
        {
            this.Duration = "PT10M";
            this.WaitTimeout = "PT1H";
            this.StopOnIdleEnd = true;
            this.RestartOnIdle = false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class restartType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string Interval;

        /// <remarks/>
        public byte Count;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class settingsType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool AllowStartOnDemand;

        /// <remarks/>
        public restartType RestartOnFailure;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(multipleInstancesPolicyType.IgnoreNew)]
        public multipleInstancesPolicyType MultipleInstancesPolicy;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool DisallowStartIfOnBatteries;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool StopIfGoingOnBatteries;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool AllowHardTerminate;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool StartWhenAvailable;

        /// <remarks/>
        public string NetworkProfileName;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool RunOnlyIfNetworkAvailable;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool WakeToRun;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Enabled;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Hidden;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0S")]
        public string DeleteExpiredTaskAfter;

        /// <remarks/>
        public idleSettingsType IdleSettings;

        /// <remarks/>
        public networkSettingsType NetworkSettings;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT72H")]
        public string ExecutionTimeLimit;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(sbyte), "7")]
        public sbyte Priority;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool RunOnlyIfIdle;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UseUnifiedSchedulingEngine;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DisallowStartOnRemoteAppSession;

        public settingsType()
        {
            this.AllowStartOnDemand = true;
            this.MultipleInstancesPolicy = multipleInstancesPolicyType.IgnoreNew;
            this.DisallowStartIfOnBatteries = true;
            this.StopIfGoingOnBatteries = true;
            this.AllowHardTerminate = true;
            this.StartWhenAvailable = false;
            this.RunOnlyIfNetworkAvailable = false;
            this.WakeToRun = false;
            this.Enabled = true;
            this.Hidden = false;
            this.DeleteExpiredTaskAfter = "PT0S";
            this.ExecutionTimeLimit = "PT72H";
            this.Priority = ((sbyte)(7));
            this.RunOnlyIfIdle = false;
            this.UseUnifiedSchedulingEngine = false;
            this.DisallowStartOnRemoteAppSession = false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public enum multipleInstancesPolicyType
    {

        /// <remarks/>
        Parallel,

        /// <remarks/>
        Queue,

        /// <remarks/>
        IgnoreNew,

        /// <remarks/>
        StopExisting,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class monthlyDayOfWeekScheduleType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Week", IsNullable = false)]
        public string[] Weeks;

        /// <remarks/>
        public daysOfWeekType DaysOfWeek;

        /// <remarks/>
        public monthsType Months;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class daysOfWeekType
    {

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object Monday;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object Tuesday;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object Wednesday;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object Thursday;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object Friday;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object Saturday;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object Sunday;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class monthsType
    {

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object January;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object February;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object March;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object April;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object May;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object June;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object July;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object August;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object September;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object October;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object November;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object December;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class monthlyScheduleType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Day", IsNullable = false)]
        public string[] DaysOfMonth;

        /// <remarks/>
        public monthsType Months;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class weeklyScheduleType
    {

        /// <remarks/>
        public byte WeeksInterval;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeeksIntervalSpecified;

        /// <remarks/>
        public daysOfWeekType DaysOfWeek;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class dailyScheduleType
    {

        /// <remarks/>
        public uint DaysInterval;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DaysIntervalSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class namedValue
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class repetitionType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string Interval;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string Duration;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool StopAtDurationEnd;

        public repetitionType()
        {
            this.StopAtDurationEnd = false;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(calendarTriggerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sessionStateChangeTriggerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(logonTriggerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(eventTriggerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(timeTriggerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(idleTriggerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(registrationTriggerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(bootTriggerType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public abstract partial class triggerBaseType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Enabled;

        /// <remarks/>
        public System.DateTime StartBoundary;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartBoundarySpecified;

        /// <remarks/>
        public System.DateTime EndBoundary;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndBoundarySpecified;

        /// <remarks/>
        public repetitionType Repetition;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT72H")]
        public string ExecutionTimeLimit;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string id;

        public triggerBaseType()
        {
            this.Enabled = true;
            this.ExecutionTimeLimit = "PT72H";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class calendarTriggerType : triggerBaseType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0M")]
        public string RandomDelay;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScheduleByDay", typeof(dailyScheduleType))]
        [System.Xml.Serialization.XmlElementAttribute("ScheduleByMonth", typeof(monthlyScheduleType))]
        [System.Xml.Serialization.XmlElementAttribute("ScheduleByMonthDayOfWeek", typeof(monthlyDayOfWeekScheduleType))]
        [System.Xml.Serialization.XmlElementAttribute("ScheduleByWeek", typeof(weeklyScheduleType))]
        public object Item;

        public calendarTriggerType()
        {
            this.RandomDelay = "PT0M";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class sessionStateChangeTriggerType : triggerBaseType
    {

        /// <remarks/>
        public string UserId;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0M")]
        public string Delay;

        /// <remarks/>
        public sessionStateChangeType StateChange;

        public sessionStateChangeTriggerType()
        {
            this.Delay = "PT0M";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public enum sessionStateChangeType
    {

        /// <remarks/>
        ConsoleConnect,

        /// <remarks/>
        ConsoleDisconnect,

        /// <remarks/>
        RemoteConnect,

        /// <remarks/>
        RemoteDisconnect,

        /// <remarks/>
        SessionLock,

        /// <remarks/>
        SessionUnlock,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class logonTriggerType : triggerBaseType
    {

        /// <remarks/>
        public string UserId;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0M")]
        public string Delay;

        public logonTriggerType()
        {
            this.Delay = "PT0M";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class eventTriggerType : triggerBaseType
    {

        /// <remarks/>
        public string Subscription;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0M")]
        public string Delay;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0M")]
        public string PeriodOfOccurrence;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "1")]
        public byte NumberOfOccurrences;

        /// <remarks/>
        public string MatchingElement;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Value", IsNullable = false)]
        public namedValue[] ValueQueries;

        public eventTriggerType()
        {
            this.Delay = "PT0M";
            this.PeriodOfOccurrence = "PT0M";
            this.NumberOfOccurrences = ((byte)(1));
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class timeTriggerType : triggerBaseType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0M")]
        public string RandomDelay;

        public timeTriggerType()
        {
            this.RandomDelay = "PT0M";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class idleTriggerType : triggerBaseType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class registrationTriggerType : triggerBaseType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0M")]
        public string Delay;

        public registrationTriggerType()
        {
            this.Delay = "PT0M";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class bootTriggerType : triggerBaseType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0M")]
        public string Delay;

        public bootTriggerType()
        {
            this.Delay = "PT0M";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class triggersType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BootTrigger", typeof(bootTriggerType))]
        [System.Xml.Serialization.XmlElementAttribute("CalendarTrigger", typeof(calendarTriggerType))]
        [System.Xml.Serialization.XmlElementAttribute("EventTrigger", typeof(eventTriggerType))]
        [System.Xml.Serialization.XmlElementAttribute("IdleTrigger", typeof(idleTriggerType))]
        [System.Xml.Serialization.XmlElementAttribute("LogonTrigger", typeof(logonTriggerType))]
        [System.Xml.Serialization.XmlElementAttribute("RegistrationTrigger", typeof(registrationTriggerType))]
        [System.Xml.Serialization.XmlElementAttribute("SessionStateChangeTrigger", typeof(sessionStateChangeTriggerType))]
        [System.Xml.Serialization.XmlElementAttribute("TimeTrigger", typeof(timeTriggerType))]
        public triggerBaseType[] Items;
    }
}
